name: Code quality CI

on:
  push:
    branches: ["feature/**", "dev", "main"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  lint:
    name: Python Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Run Ruff checks
      run: |
        uvx ruff check .
        uvx ruff format --check .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with: { version: latest }

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-venv-

      - name: Install deps (with test extra)
        run: uv sync --extra test  # installs base + test deps into .venv

      - name: Run unit tests
        run: |
          mkdir -p reports
          # Show coverage table in logs AND save to reports/coverage.txt
          PYTHONPATH=$PWD uv run pytest tests \
            --cov=src \
            --cov-report=term-missing | tee reports/coverage.txt

      - name: Upload coverage report
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_id }}
          path: reports/coverage.txt
